const express = require('express');
const cors = require('cors');
const parse = require('pg-connection-string').parse;
const http = require('http');

const { Pool } = require('pg');

const config = parse('postgres://me:password@localhost:5432/movement')

const pool = new Pool(config);

const app = express();

app.use(
  cors({
    origin: '*',
  })
);

app.get('/build-data', (req, res) => res.send('This is working'));

const port = 8000;
const server = http.createServer(app);
server.listen(port);
console.log('Server listening on:', port);



async function setUpTables(request, response) {
  
  const createUserTable = `
    CREATE TABLE "movers" (
      user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email varchar,
      name varchar,
      password varchar
    );`;
  
  await pool.query(createUserTable).catch((err) => {
    console.log(err);
  })

}

const addUser = (req, res, next) => {
  const query = {
    text: `
    INSERT INTO movers (email, name, password)
      VALUES ($1, $2, $3)
    `,
    values: ['dio@hello.com, dio, password1']
  };
  
  pool.query(query, (err, results) => {
    if (err) {
      throw err;
    }
    res.send(results.rows);
  });
};